### PR TITLE
Update main.css

### PR DESCRIPTION
**Pull request by marcoooo**
Update inner table max width.

### CODE REVIEW

**Comment by muffato** [comment]
What about using `overflow: auto` to automatically add a scrollbar if needed ? https://www.w3schools.com/css/css_overflow.asp

**Comment by marcoooo** [comment]
> What about using `overflow: auto` to automatically add a scrollbar if needed ? https://www.w3schools.com/css/css_overflow.asp

as far as I know, this is not possible for a table cell, only if you set a div inside with the scroll and fix the width of the TD

**Comment by muffato** [comment]
Indeed:https://stackoverflow.com/questions/1211309/overflowscroll-in-td

**Comment by marcoooo** [comment]
Warning: potential side effect with such a general TD css update:
In the 'Pipelinewide parameters' panel, button for updating values is hidden.

**Comment by marcoooo** [comment]
Hi, any idea when this would be merged?

**Comment by ens-bwalts** [comment]
Could you make this against base branch db_version/62, and we'll cascade-merge it up.

**Comment by marcoooo** [comment]
> Could you make this against base branch db_version/62, and we'll cascade-merge it up.

Sure :-)

**Comment by marcoooo** [comment]
> > Could you make this against base branch db_version/62, and we'll cascade-merge it up.
> 
> Sure :-)

Well... I've got many more file included now.

**Comment by marcoooo** [comment]
Moved to https://github.com/Ensembl/guiHive/pull/3

**Pull request closed without merging**
